name: 'Run e2e with pw'

on:
  push:
  pull_request:
  workflow_dispatch:

# If you push multiple commits in quick succession, cancel older runs
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  # 1) Burn-in job (only runs on pull_request)
  pw-burn-in:
    if: ${{ github.event_name == 'pull_request' }}
    uses: ./.github/workflows/burn-in-reusable.yml
    with:
      # We'll pass in the base ref from the PR, e.g. "main"
      # Some orgs do "develop" or other branches. Adjust as needed.
      base-ref: ${{ github.base_ref }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  # 2) Full E2E job
  pw-e2e:
    # Wait for the burn-in job to finish or skip
    needs: [pw-burn-in]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]
    steps:
      - uses: actions/checkout@v4
        with:
          # For PRs: checkout PR head. For push: checkout that commit.
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Read Node version from .nvmrc
        id: node_version
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache Playwright Browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            playwright-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Chromium Only
        run: npx playwright install chromium

      - name: Run PW e2e tests (sharded)
        run: npx playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}

      - name: Copy trace files to blob-report
        run: |
          mkdir -p blob-report/trace
          cp -r test-results/**/*.zip blob-report/trace || true

      - name: Upload shard blob report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: blob-report-${{ matrix.shardIndex }}
          path: blob-report
          retention-days: 3

  # 3) Merge the reports
  merge-reports:
    needs: [pw-burn-in, pw-e2e]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Download shard reports
        uses: actions/download-artifact@v4
        with:
          path: all-blob-reports
          pattern: blob-report-*
          merge-multiple: true

      - name: Merge Playwright reports
        run: |
          mkdir -p playwright-report/trace
          cp -r all-blob-reports/*/trace/* playwright-report/trace || true
          npx playwright merge-reports --reporter=html all-blob-reports

      - name: Upload merged report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 3
