name: PR E2E Checks

on:
  pull_request:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      found_changed: ${{ steps.diff-check.outputs.found_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          # So we can do a proper diff against base
          fetch-depth: 0

      - id: diff-check
        run: |
          # Compare HEAD with the PR’s base branch
          git fetch origin ${{ github.base_ref }} --depth=1
          changed_files=$(git diff --name-only origin/${{ github.base_ref }} HEAD)

          echo "Changed files:"
          echo "$changed_files"

          # Check if anything in 'pw/' folder changed with .spec.ts or .test.ts
          if echo "$changed_files" | grep -Eq '^pw/.*\.(spec|test)\.ts'; then
            echo "found_changed=true"
            echo "::set-output name=found_changed::true"
          else
            echo "found_changed=false"
            echo "::set-output name=found_changed::false"
          fi

  pw-burn-in:
    # Only run if detect-changes says 'true'
    needs: [detect-changes]
    if: ${{ needs.detect-changes.outputs.found_changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read Node version from .nvmrc
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright (Chromium only)
        run: npx playwright install chromium

      - name: Run Burn-in
        # If this fails (exit code != 0), the job status is “failure.”
        run: |
          npx playwright test \
            --only-changed=${{ github.base_ref }} \
            --repeat-each=5 \
            --retries=0

  pw-e2e:
    needs:
      - detect-changes
      - pw-burn-in
    # Always evaluate this job, but only skip if Burn-in actually ran and failed.
    # If Burn-in was skipped, that’s not a “failure,” so we proceed.
    if: ${{ always() && (needs.pw-burn-in.result != 'failure') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read Node version from .nvmrc
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright (Chromium only)
        run: npx playwright install chromium

      - name: Run Full E2E
        run: npx playwright test
